app:
    env: dev
    cache: false
    machine-id: 1
    service-name: domain
    server-port: 7080
    api-prefix: /domain
jwt:
    access-expire: 7200
    refresh-expire: 86400
    issuer: sni
    asecret: Pe2a23F!afGQW9xC3ks16Tzr5g#jW(@t
    rsecret: IZvo$ce%G^53DTa5V9+N66nH(k*_QW3+
postgres:
    database: distri_domain
    host: 129.150.39.115
    port: 5432
    user: distri_domain
    password: 7WM84ZYtyHYThQDX
mail:
    smtp-server:
    smtp-port:
    email-writer:
    email-bcc:
    email-cc:
    account:
    password:
    url-prefix: